# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/louis/vivado/misc/misc.cache/wt [current_project]
set_property parent.project_path C:/Users/louis/vivado/misc/misc.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
add_files C:/Users/louis/vivado/misc/misc.srcs/sources_1/ram.coe
add_files -quiet C:/Users/louis/vivado/misc/misc.srcs/sources_1/ip/ram/ram.dcp
set_property used_in_implementation false [get_files C:/Users/louis/vivado/misc/misc.srcs/sources_1/ip/ram/ram.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/louis/vivado/misc/misc.srcs/sources_1/new/processor.vhd
  C:/Users/louis/vivado/misc/misc.srcs/sources_1/new/misc.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/louis/vivado/misc/misc.srcs/constrs_1/imports/vivado/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/louis/vivado/misc/misc.srcs/constrs_1/imports/vivado/Basys3_Master.xdc]


synth_design -top misc -part xc7a35tcpg236-1


write_checkpoint -force -noxdef misc.dcp

catch { report_utilization -file misc_utilization_synth.rpt -pb misc_utilization_synth.pb }
